In [1]:
# Importing numpy library
import numpy as np

In [4]:
input_list = [2,4,5,3,2,5,2,6,2]

In [31]:
converted_list = np.array(input_list)
print(converted_list)
print(type(converted_list))
arr = converted_list.reshape(3,3)
print(arr)

arr.mean(axis=0).tolist(), arr.mean(axis=1), arr.mean()




[2 4 5 3 2 5 2 6 2]
<class 'numpy.ndarray'>
[[2 4 5]
 [3 2 5]
 [2 6 2]]


([2.3333333333333335, 4.0, 4.0],
 array([3.66666667, 3.33333333, 3.33333333]),
 3.4444444444444446)

In [38]:
def calculate(input_list):
    result = {}
    try:
        if len(input_list) < 9:
            raise ValueError
        else:
            converted_list = np.array(input_list)
            list_as_array = converted_list.reshape(3,3)
            
            result['mean'] = [list_as_array.mean(axis=0).tolist(), list_as_array.mean(axis=1).tolist(), list_as_array.mean().tolist()]
            result['variance'] = [list_as_array.var(axis=0).tolist(), list_as_array.var(axis=1).tolist(), list_as_array.var().tolist()]
            result['standard deviation'] = [list_as_array.std(axis=0).tolist(), list_as_array.std(axis=1).tolist(), list_as_array.std().tolist()]
            result['max'] = [list_as_array.max(axis=0).tolist(), list_as_array.max(axis=1).tolist(), list_as_array.max().tolist()]
            result['min'] = [list_as_array.min(axis=0).tolist(), list_as_array.min(axis=1).tolist(), list_as_array.min().tolist()]
            result['sum'] = [list_as_array.sum(axis=0).tolist(), list_as_array.sum(axis=1).tolist(), list_as_array.sum().tolist()]
            
    return result
#     except ValueError:
#         print(f"List must contain nine numbers")

SyntaxError: invalid syntax (Temp/ipykernel_404/384297264.py, line 17)

In [37]:
calculate(input_list)

{'mean': [[2.3333333333333335, 4.0, 4.0],
  [3.6666666666666665, 3.3333333333333335, 3.3333333333333335],
  3.4444444444444446],
 'variance': [[0.22222222222222224, 2.6666666666666665, 2.0],
  [1.5555555555555554, 1.5555555555555554, 3.555555555555556],
  2.2469135802469133],
 'standard deviation': [[0.4714045207910317,
   1.632993161855452,
   1.4142135623730951],
  [1.247219128924647, 1.247219128924647, 1.8856180831641267],
  1.4989708403591155],
 'max': [[3, 6, 5], [5, 5, 6], 6],
 'min': [[2, 2, 2], [2, 2, 2], 2],
 'sum': [[7, 12, 12], [11, 10, 10], 31]}

In [34]:
l = [3,4,4,5]

In [35]:
calculate(l)

List must contain nine numbers


In [43]:
if len(l) < 9:
    raise ValueError("List must contain nine numbers.")

ValueError: List must contain nine numbers.