## Numpy

# Why Numpy is faster? 

- Less bytes of memory
- No Type checking 
- continous memory
- SIMD Vector Processing 


In [4]:
a = [1,2,3]
b = [3,4,5]

In [5]:
#a*b # Error

In [6]:
import numpy as np

In [7]:
c = np.array([1,2,3])
d = np.array([3,5,3])
c*d

array([ 3, 10,  9])

In [8]:
a = np.array([[9.0,8,7.0], [6.0,5.0,4]], dtype='int32')

In [9]:
a


array([[9, 8, 7],
       [6, 5, 4]])

In [10]:
a.ndim

2

In [11]:
a.shape

(2, 3)

In [12]:
 #Get Type
    
a.dtype

dtype('int32')

In [13]:
a.itemsize

4

In [14]:
a.size

6

In [15]:
a.nbytes

24

In [16]:
a = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
a[:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [18]:
a[0:1]

array([[1, 2, 3, 4, 5]])

In [19]:
# [r,c]

In [20]:
a[0,2] = 20

In [21]:
a

array([[ 1,  2, 20,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [22]:
a[:,2] = 20

In [23]:
a

array([[ 1,  2, 20,  4,  5],
       [ 6,  7, 20,  9, 10]])

In [24]:
b = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

In [25]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [26]:
b.shape, b.ndim

((2, 2, 2), 3)

In [27]:
b[0,1,1]

4

In [28]:
b[:,0,:]

array([[1, 2],
       [5, 6]])

In [31]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [33]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [36]:
# full_alike
b=np.full_like(a,4)
b

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [39]:
np.random.rand(4,2,3
              )

array([[[4.08611509e-01, 7.78923128e-01, 2.88348102e-01],
        [5.72133078e-01, 6.04834815e-01, 9.84412650e-01]],

       [[2.49393526e-01, 6.85040301e-01, 6.24641021e-01],
        [8.79031335e-01, 9.97797762e-01, 3.31417577e-01]],

       [[3.30603835e-04, 7.85904875e-01, 8.55077456e-01],
        [1.09239399e-01, 8.37282605e-01, 3.77411845e-01]],

       [[8.97258251e-01, 3.30789000e-01, 4.02286038e-01],
        [3.71483019e-01, 1.37053106e-01, 8.44054332e-02]]])

In [47]:
# Random Integer Value
np.random.randint(97, size=(3,3))

array([[17, 72, 46],
       [24, 45, 60],
       [80, 37, 78]])

In [48]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [57]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [61]:
output = np.ones((5,5))

In [68]:
z = np.zeros((3,3))
print(z)
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [77]:
output = np.zeros((7,7))
print(output)
ones = np.ones((5,5))
ones[2,2] = 5
print(ones)

output[1:6, 1:6] = ones
print(output)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 5. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 5. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


## Copying

In [80]:
a = np.ones(4)
a

array([1., 1., 1., 1.])

In [81]:
b = a
b

array([1., 1., 1., 1.])

In [82]:
b [2] =20

In [83]:
a


array([ 1.,  1., 20.,  1.])

In [84]:
b

array([ 1.,  1., 20.,  1.])

In [85]:
c = a.copy()

In [86]:
c

array([ 1.,  1., 20.,  1.])

In [87]:
c[1]=100

In [88]:
c

array([  1., 100.,  20.,   1.])

In [89]:
c

array([  1., 100.,  20.,   1.])

In [90]:
a

array([ 1.,  1., 20.,  1.])

## Mathematics

In [100]:
a = np.array([1,2,3,4])

In [92]:
a

array([1, 2, 3, 4])

In [93]:
a + 2

array([3, 4, 5, 6])

In [94]:
a*2

array([2, 4, 6, 8])

In [95]:
a-2

array([-1,  0,  1,  2])

In [96]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [97]:
a +=2

In [101]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [102]:
a

array([1, 2, 3, 4])

In [104]:
a **2

array([ 1,  4,  9, 16], dtype=int32)

In [105]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [106]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

#### Linear Algebra

In [110]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [112]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [113]:
c = np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

In [124]:
stats = np.random.randint(10,52, size=(10,10))
stats

array([[25, 39, 44, 27, 33, 35, 49, 23, 26, 49],
       [11, 19, 29, 47, 29, 29, 12, 32, 22, 40],
       [43, 40, 38, 33, 19, 28, 39, 12, 25, 38],
       [43, 37, 24, 26, 40, 12, 50, 41, 31, 37],
       [25, 36, 28, 21, 30, 14, 11, 21, 23, 30],
       [38, 11, 38, 18, 23, 45, 30, 30, 11, 12],
       [29, 37, 19, 41, 12, 29, 27, 23, 22, 48],
       [44, 34, 20, 44, 10, 26, 50, 16, 49, 33],
       [17, 17, 43, 28, 24, 15, 31, 29, 48, 41],
       [47, 11, 36, 14, 31, 26, 36, 36, 19, 28]])

In [125]:
stats.T

array([[25, 11, 43, 43, 25, 38, 29, 44, 17, 47],
       [39, 19, 40, 37, 36, 11, 37, 34, 17, 11],
       [44, 29, 38, 24, 28, 38, 19, 20, 43, 36],
       [27, 47, 33, 26, 21, 18, 41, 44, 28, 14],
       [33, 29, 19, 40, 30, 23, 12, 10, 24, 31],
       [35, 29, 28, 12, 14, 45, 29, 26, 15, 26],
       [49, 12, 39, 50, 11, 30, 27, 50, 31, 36],
       [23, 32, 12, 41, 21, 30, 23, 16, 29, 36],
       [26, 22, 25, 31, 23, 11, 22, 49, 48, 19],
       [49, 40, 38, 37, 30, 12, 48, 33, 41, 28]])

In [127]:
stats.max()

50

In [129]:
stats.min()

10

In [130]:
np.max(stats, axis=0)

array([47, 40, 44, 47, 40, 45, 50, 41, 49, 49])

In [131]:
np.max(stats, axis=1)

array([49, 47, 43, 50, 36, 45, 48, 50, 48, 47])

In [132]:
np.sum(stats)

2961

In [134]:
a = np.array(([1,2,3,4,5], 
[6,7,8,9,10]))
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [136]:
np.max(a, axis=1)

array([ 5, 10])

In [138]:
np.max(a, axis =1).sum()

15

In [139]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [147]:
##### before = a.copy()
print(before)
print(f"Shape is{before.shape}")

after = before.reshape((5,2))
print(after)
print(f"Shape is{after.shape}")

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Shape is(2, 5)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
Shape is(5, 2)


In [150]:
## Vertically stacking
v1 = np.array([1,2,3,4])
v2 = np.array([1,5,3,5])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [1, 5, 3, 5],
       [1, 2, 3, 4],
       [1, 5, 3, 5]])

In [149]:
## Horizontal stacking
v1 = np.array([1,2,3,4])
v2 = np.array([1,5,3,5])

np.hstack([v1,v2,v1])

array([1, 2, 3, 4, 1, 5, 3, 5, 1, 2, 3, 4])

In [152]:
a = np.ones((2,4))
print(a)
b = a.reshape(4,2)
print(b
     )

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


## Loading data from file

In [154]:
a = np.random.randint(0,100, size=(3,10))
a

array([[86, 62, 56, 94, 43, 32, 38, 24, 42, 99],
       [69, 41, 16, 19, 84, 71, 60, 17, 40, 48],
       [18, 97, 83, 86, 36, 69,  6, 91, 54, 99]])

In [156]:
filedata = np.genfromtxt('data/data.txt', delimiter=',')
filedata

array([[86., 62., 56., 94., 43., 32., 38., 24., 42., 99.],
       [69., 41., 16., 19., 84., 71., 60., 17., 40., 48.],
       [18., 97., 83., 86., 36., 69.,  6., 91., 54., 99.]])

In [157]:
a = filedata.astype('int32')
a

array([[86, 62, 56, 94, 43, 32, 38, 24, 42, 99],
       [69, 41, 16, 19, 84, 71, 60, 17, 40, 48],
       [18, 97, 83, 86, 36, 69,  6, 91, 54, 99]])

#### Advance Indexing

In [158]:
filedata > 50


array([[ True,  True,  True,  True, False, False, False, False, False,
         True],
       [ True, False, False, False,  True,  True,  True, False, False,
        False],
       [False,  True,  True,  True, False,  True, False,  True,  True,
         True]])

In [159]:
filedata[filedata>50]

array([86., 62., 56., 94., 99., 69., 84., 71., 60., 97., 83., 86., 69.,
       91., 54., 99.])

In [178]:
a= np.random.randint(10,size = (1,10))
a

array([[4, 0, 3, 3, 0, 1, 5, 7, 6, 6]])

In [179]:
b = np.array([0, 9, 4, 8, 8, 0, 8, 9, 8, 4])
b

array([0, 9, 4, 8, 8, 0, 8, 9, 8, 4])

In [180]:
b[[2,3,9]]

array([4, 8, 4])

In [181]:
np.any(filedata>50, axis =0)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [189]:
a = np.array(range(1,31)).reshape(6,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [192]:
a[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [194]:
a[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [196]:
a[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [205]:
b = [[29,97,32,100,45]
,[15,88,5,75,22]]
b= np.array(b)

In [206]:
type(b)

numpy.ndarray

In [208]:
output = b[b<50]
output

array([29, 32, 45, 15,  5, 22])